### ISSUE TITLE
More info needed

### ISSUE THREAD

**Issue by toncho11** [lora-aprs/LoRa_APRS_Tracker#95]
I have a few questions:
- Can I use two LoRa APRS trackers to communicate between them?
- Can I use Bluetooth to connect each of them to a laptop (one laptop at home with LoRa APRS tracker, one laptop at work with LoRa APRS tracker)? In the  case of laptop there will be software to perform the communication?

**Comment by richonguzman** [comment]
It seems you are looking for "Meshtastic" as a solution, as this firmware uses the T-Beam boards and let you do the messaging part your are looking for

o is it that your are looking to do this over/through APRS also?

**Comment by peterus** [comment]
Currently this Firmware has no support to send messages over the APRS network. My iGate Firmware is already supporting message forwarding (no creating of messages) from HF to APRS-IS, HF to HF and from APRS-IS to HF.

Support for the Tracker will be soon added.

**Comment by richonguzman** [comment]
I guess this is already done with the Meshtastic firmware for T-Beam boards:

Point to point Message with kiss tnc

Although If you need to go through APRS , you’ll have to mode the script yourself ir wait for someone to do this

El 22-03-2023, a las 11:56, toncho11 ***@***.***> escribió:

﻿

The idea is to have an alternative application. So instead of "tracker" to have a "messenger" or "APRS messenger".
The idea is to have point to point communication.
I could use it between my work and my home. Send messages from remote parts of the mountain or in case of outage of the 3G/4G networks.
Please consider this possible development.
